version: 2.1
orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn dev
        name: Run dev server
      - run:
        command: yarn test
        name: Tests the app
      - persist_to_workspace:
        root: ~/project
        paths:
          - .

      deploy:
        - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $SITE_ID --auth $CIRCLE_CI --prod --dir=build

workflows:
  version: 2
  build-deploy:
  jobs:
    - build_and_test:
      filters:
        branches:
          only:
            - main
